#!/bin/sh
# by Martin Seeler, modified by Joe Murray

# destination of the final changelog file
OUTPUT_FILE=CHANGELOG.md

# paste the source url of your git repository
REPO_URL=https://github.com/JMAConsulting/auto-changelog-hook

# generate the changelog
# Change the repo link here to the one for the extension you are installing this in
git --no-pager log --no-merges --format="%n #### %ai [%s](${REPO_URL}/commit/%H) Author: %aN Committer: %cN <br><br>" > $OUTPUT_FILE

# prevent recursion!
# since a 'commit --amend' will trigger the post-commit script again
# we have to check if the changelog file has changed or not
# use fix for subfolders from https://github.com/thorian93/auto-changelog-hook/commit/a7fd7496aef1bedde85834a51114ec37e8e9c856
res=$(git status --porcelain | grep ".\ $OUTPUT_FILE$" | wc -l)
if [ "$res" -gt 0 ]; then
  git add $OUTPUT_FILE
  git commit --amend
  echo "Populated Changelog in $OUTPUT_FILE"
fi
